import { lstat, readFile } from "node:fs/promises";
import path from "node:path";

const VERSION=1, MAX_REQUEST_BYTES=16*1024, MAX_STATUS_BYTES=128*1024, MAX_ROUNDS=64, MAX_LABEL=8;
const SCHEMA="studylink.runtime-status.v1";
const PHASES=new Set(["dependency","facts","declarations","document-association","unknown"]);
const RESIDUALS=new Set(["ambiguous-checkbox","ambiguous-date-control","ambiguous-document-rule","ambiguous-semantic-rule","answer-kind-mismatch","accepted-save-not-persisted","canonical-value-already-populated","compound-date-incomplete","date-out-of-range","date-part-format-unavailable","document-occurrence-bound","document-runtime-constraint","document-slot-already-occupied","document-slot-not-active","exact-option-unavailable","insufficient-semantic-context","isolated-or-prior-attempt","max-stage-bound-reached","no-authorized-declaration-answer","no-profile-fact","no-synthetic-document-rule","pretransport-isolated","prior-ambiguous-transport-excluded","profile-date-invalid","provider-atomic-validation-boundary","profile-value-pattern-mismatch","profile-value-too-long","progression-action","prohibited-signature-declaration","prompt-unresolved","protected-semantic-category","repeater-action-not-scalar","required-declaration-document-unavailable","runtime-pattern-invalid","timeout-reconciled-not-persisted","unchecked-answer-conflicts-with-populated-control","validation-no-persistence","unknown"]);
const PUBLIC={invalid_request:"The StudyLink status request is invalid.",method_not_allowed:"The requested StudyLink method is not allowed.",status_invalid:"The controlled StudyLink status is invalid.",status_unavailable:"The controlled StudyLink status is unavailable."};
class RpcError extends Error{constructor(code){super(PUBLIC[code]);this.code=code}}
const record=v=>v!==null&&typeof v==="object"&&!Array.isArray(v);
const exact=(v,keys)=>record(v)&&Object.keys(v).sort().join("|")===keys.slice().sort().join("|");
const count=v=>Number.isSafeInteger(v)&&v>=0&&v<=1_000_000?v:null;
const ms=v=>Number.isSafeInteger(v)&&v>=0&&v<=86_400_000?v:null;
const iso=v=>typeof v==="string"&&Number.isFinite(Date.parse(v))&&v===new Date(v).toISOString();
function statusDirectory(){const d=process.env.WORLD_PLUGIN_STATE_DIR;if(typeof d!=="string"||!path.isAbsolute(d)||d.length>4096)throw new RpcError("status_unavailable");return d}
function validate(raw){
 if(!exact(raw,["schema","runId","lifecycle","timestamps","rail","phase","target","rounds","invariants","ordinaryCompletion","residualReasonCounts","terminal","provenance"])||raw.schema!==SCHEMA)throw new RpcError("status_invalid");
 if(typeof raw.runId!=="string"||!/^[0-9a-f-]{36}$/.test(raw.runId)||!["running","completed","failed"].includes(raw.lifecycle)||!["new-form","legacy"].includes(raw.rail)||typeof raw.phase!=="string"||raw.phase.length>40)throw new RpcError("status_invalid");
 const t=raw.timestamps;if(!exact(t,["startedAt","updatedAt","heartbeatAt","terminalAt","staleAfterMs"])||![t.startedAt,t.updatedAt,t.heartbeatAt].every(iso)||(t.terminalAt!==null&&!iso(t.terminalAt))||ms(t.staleAfterMs)===null||t.staleAfterMs<1000)throw new RpcError("status_invalid");
 let target=null;if(raw.target!==null){if(!exact(raw.target,["label"])||typeof raw.target.label!=="string"||raw.target.label.length>MAX_LABEL||!/^[A-Z][1-9][0-9]{0,2}$/.test(raw.target.label))throw new RpcError("status_invalid");target={label:raw.target.label}}
 if(!Array.isArray(raw.rounds)||raw.rounds.length>MAX_ROUNDS)throw new RpcError("status_invalid");
 const rounds=raw.rounds.map(r=>{if(!exact(r,["round","phase","selected","persisted","save","freshReadback","timingMs"])||count(r.round)===null||r.round<1||!PHASES.has(r.phase)||count(r.selected)===null||count(r.persisted)===null)throw new RpcError("status_invalid");if(!exact(r.save,["attempted","outcome"])||typeof r.save.attempted!=="boolean"||!["accepted","validation","reconciled-after-timeout","not-attempted","unknown"].includes(r.save.outcome))throw new RpcError("status_invalid");if(!exact(r.freshReadback,["observed","persisted"])||typeof r.freshReadback.observed!=="boolean"||count(r.freshReadback.persisted)===null)throw new RpcError("status_invalid");if(!exact(r.timingMs,["save","total"])||ms(r.timingMs.save)===null||(r.timingMs.total!==null&&ms(r.timingMs.total)===null))throw new RpcError("status_invalid");return {round:r.round,phase:r.phase,selected:r.selected,persisted:r.persisted,save:{attempted:r.save.attempted,outcome:r.save.outcome},freshReadback:{observed:r.freshReadback.observed,persisted:r.freshReadback.persisted},timingMs:{save:r.timingMs.save,total:r.timingMs.total}}});
 const i=raw.invariants;if(!exact(i,["baselinePreserved","selectedOnlyOrNormalized","overwrite","freshReadbackRequired"])||typeof i.baselinePreserved!=="boolean"||typeof i.selectedOnlyOrNormalized!=="boolean"||i.overwrite!==false||i.freshReadbackRequired!==true)throw new RpcError("status_invalid");
 const c=raw.ordinaryCompletion;if(!exact(c,["answered","denominator","percentage"])||count(c.answered)===null||count(c.denominator)===null||typeof c.percentage!=="number"||!Number.isFinite(c.percentage)||c.percentage<0||c.percentage>100)throw new RpcError("status_invalid");
 if(!record(raw.residualReasonCounts)||Object.keys(raw.residualReasonCounts).length>RESIDUALS.size)throw new RpcError("status_invalid");const residualReasonCounts={};for(const [k,v] of Object.entries(raw.residualReasonCounts)){if(!RESIDUALS.has(k)||count(v)===null)throw new RpcError("status_invalid");if(v)residualReasonCounts[k]=v}
 const terminal=raw.terminal;if(!exact(terminal,["terminal","failClosed","outcome","reason"])||typeof terminal.terminal!=="boolean"||typeof terminal.failClosed!=="boolean"||!["running","completed","failed"].includes(terminal.outcome)||!["none","runtime-error"].includes(terminal.reason))throw new RpcError("status_invalid");
 const p=raw.provenance;if(!exact(p,["cli","command","packageVersion","buildCommit"])||p.cli!=="studylink"||p.command!=="autonomous-save"||typeof p.packageVersion!=="string"||p.packageVersion.length>40||!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(p.packageVersion)||(p.buildCommit!==null&&(typeof p.buildCommit!=="string"||!/^[a-f0-9]{7,40}$/.test(p.buildCommit))))throw new RpcError("status_invalid");
 return {schema:SCHEMA,lifecycle:raw.lifecycle,timestamps:{startedAt:t.startedAt,updatedAt:t.updatedAt,heartbeatAt:t.heartbeatAt,terminalAt:t.terminalAt,staleAfterMs:t.staleAfterMs},rail:raw.rail,phase:raw.phase,target,rounds,invariants:{baselinePreserved:i.baselinePreserved,selectedOnlyOrNormalized:i.selectedOnlyOrNormalized,overwrite:false,freshReadbackRequired:true},ordinaryCompletion:{answered:c.answered,denominator:c.denominator,percentage:c.percentage},residualReasonCounts,terminal:{terminal:terminal.terminal,failClosed:terminal.failClosed,outcome:terminal.outcome,reason:terminal.reason},provenance:{cli:"studylink",command:"autonomous-save",packageVersion:p.packageVersion,buildCommit:p.buildCommit}};
}
function idle(){return {availability:"idle",snapshot:null,synthetic:false}}
async function readControlled(){const file=path.join(statusDirectory(),"runtime-status.json");try{const s=await lstat(file);if(!s.isFile()||s.isSymbolicLink()||s.size>MAX_STATUS_BYTES)throw new RpcError("status_invalid");const snapshot=validate(JSON.parse(await readFile(file,"utf8")));const stale=!snapshot.terminal.terminal&&Date.now()-Date.parse(snapshot.timestamps.heartbeatAt)>snapshot.timestamps.staleAfterMs;return {availability:stale?"stale":snapshot.lifecycle,snapshot,synthetic:false}}catch(e){if(e?.code==="ENOENT")return idle();if(e instanceof SyntaxError)throw new RpcError("status_invalid");if(e instanceof RpcError)throw e;throw new RpcError("status_unavailable")}}
function demo(tick){const terminal=tick>=3, n=Math.min(tick,3), now="2026-09-03T00:00:0"+n+".000Z";const snapshot=validate({schema:SCHEMA,runId:"11111111-1111-4111-8111-111111111111",lifecycle:terminal?"completed":"running",timestamps:{startedAt:"2026-09-03T00:00:00.000Z",updatedAt:now,heartbeatAt:now,terminalAt:terminal?now:null,staleAfterMs:120000},rail:"new-form",phase:terminal?"completed":n?"facts":"starting",target:{label:"A1"},rounds:n?[{round:1,phase:"facts",selected:4,persisted:4,save:{attempted:true,outcome:"accepted"},freshReadback:{observed:true,persisted:4},timingMs:{save:312,total:604}}]:[],invariants:{baselinePreserved:n>0,selectedOnlyOrNormalized:n>0,overwrite:false,freshReadbackRequired:true},ordinaryCompletion:{answered:n?12:8,denominator:20,percentage:n?60:40},residualReasonCounts:{"no-profile-fact":n?8:12},terminal:{terminal,failClosed:false,outcome:terminal?"completed":"running",reason:"none"},provenance:{cli:"studylink",command:"autonomous-save",packageVersion:"0.10.1",buildCommit:"90e4fa6e2fb55c59567c08f84fae2be4b8f16627"}});return {availability:snapshot.lifecycle,snapshot,synthetic:true}}
async function dispatch(method,params){if(method==="studylink.status.read"){if(params!==undefined&&(!exact(params,[])))throw new RpcError("invalid_request");return readControlled()}if(method==="studylink.demo.read"){if(!exact(params,["tick"])||!Number.isSafeInteger(params.tick)||params.tick<0||params.tick>3)throw new RpcError("invalid_request");return demo(params.tick)}throw new RpcError("method_not_allowed")}
async function request(){let bytes=0,chunks=[];for await(const c of process.stdin){bytes+=c.length;if(bytes>MAX_REQUEST_BYTES)throw new RpcError("invalid_request");chunks.push(c)}try{const v=JSON.parse(Buffer.concat(chunks).toString("utf8"));if(!record(v)||v.version!==VERSION||typeof v.method!=="string"||!Object.keys(v).every(k=>["version","method","params"].includes(k)))throw new RpcError("invalid_request");return v}catch(e){if(e instanceof RpcError)throw e;throw new RpcError("invalid_request")}}
try{const q=await request();const result=await dispatch(q.method,q.params);process.stdout.write(JSON.stringify({version:VERSION,ok:true,result}))}catch(e){const safe=e instanceof RpcError?e:new RpcError("status_unavailable");process.stdout.write(JSON.stringify({version:VERSION,ok:false,error:{code:safe.code,message:safe.message}}));process.exitCode=1}
